name: HealthCheck

on:
  schedule:
    - cron: '0 15 * * *'

jobs:
  check_health:
    runs-on: ubuntu-20.04
    steps:
      - name: run url health check
        uses: Jtalk/url-health-check-action@v3.2
        with:
          url: '${{github.event.repository.homepage}}health'
          max-attempts: 2
          retry-delay: 10s
      - name: notify HEALTHY (Discord)
        if: success()
        uses: rjstone/discord-webhook-notify@v1
        with:
          webhookUrl: ${{secrets.DISCORD_WEBHOOK}}
          severity: info 
          text: 'App: ${{github.event.repository.homepage}} is healthy'
      - name: notify DEAD (Discord)
        if: failure()
        uses: rjstone/discord-webhook-notify@v1
        with:
          webhookUrl: ${{secrets.DISCORD_WEBHOOK}}
          severity: error
          text: 'App: ${{github.event.repository.homepage}} might be dead'
